apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee-controller-volume-claim
  {{- include "powerpi.labels" $ }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 
  storageClassName: powerpi-storage
