apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

configMapGenerator:
- name: settings
  behavior: merge
  envs:
  - ./env.properties

# delete Let's Encrypt live
patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: cert-manager.io/v1
  kind: Issuer
  metadata:
    name: letsencrypt

# apply user configuration to ingress and issuer
replacements:
- source:
    kind: ConfigMap
    name: settings
    fieldPath: data.EXTERNAL_HOST_NAME
  targets:
  - select:
      kind: Ingress
      name: ingress
    fieldPaths:
    - spec.rules.[host=EXTERNAL_HOST_NAME].host
    - spec.tls.0.hosts.0
- source:
    kind: ConfigMap
    name: settings
    fieldPath: data.CERTIFICATE_EMAIL
  targets:
  - select:
      kind: Issuer
      name: letsencrypt-staging
    fieldPaths:
    - spec.acme.email
