apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
  {{- include "powerpi.labels" . }}
type: Opaque
data:
  {{- include "powerpi.generate-secret" (merge (dict "Params" (dict
    "Name" "oauth-secret"
    "Key" "secret"
    "Id" "client_id"
  )) . )}}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  {{- include "powerpi.labels" . }}
type: Opaque
data:
    {{- include "powerpi.generate-secret" (merge (dict "Params" (dict
    "Name" "jwt-secret"
    "Key" "secret"
  )) . )}}
---
apiVersion: v1
kind: Secret
metadata:
  name: session-secret
  {{- include "powerpi.labels" . }}
type: Opaque
data:
  {{- include "powerpi.generate-secret" (merge (dict "Params" (dict
    "Name" "session-secret"
    "Key" "secret"
  )) . )}}
