apiVersion: v1
kind: Service
metadata:
  name: deep-thought
  {{- include "powerpi.labels" . }}
spec:
  selector:
  {{- include "powerpi.selector" . | indent 2 }}
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
