// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'device': string;
  'hidden': string;
  'history': string;
  'icon': string;
  'list': string;
  'state': string;
}
export const cssExports: CssExports;
export default cssExports;
