apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./deployment.yaml
# kubectl create secret generic github-secret --from-file=password=./gh.secret --from-literal=username=TWilkin -n powerpi
