// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'control': string;
  'focus': string;
  'icon': string;
  'input': string;
  'menu': string;
  'option': string;
  'select': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
