apiVersion: v1
kind: Service
metadata:
  name: deep-thought
spec:
  selector:
    app.kubernetes.io/name: deep-thought
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: http
