// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'all-closed': string;
  'closed': string;
  'content': string;
  'drawer': string;
  'filter': string;
  'label': string;
  'open': string;
}
export const cssExports: CssExports;
export default cssExports;
