version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.7
    ports:
      - "1883:1883"
    deploy:
      replicas: 1
  
  mqtt-rest:
    image: 127.0.0.1:5000/mqtt-rest:0.0.3
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
    depends_on:
      - mosquitto
    environment:
      - MQTT_ADDRESS=mqtt://mosquitto:1883
  
  power-starter:
    image: 127.0.0.1:5000/power-starter:0.1.0
    deploy:
      replicas: 1
    depends_on:
      - mosquitto
    environment:
      - MQTT_ADDRESS=mqtt://mosquitto:1883
  
  freedns:
    image: 127.0.0.1:5000/freedns:0.0.1
    deploy:
      replicas: 2
    secrets:
      - freedns
    environment:
      - FREEDNS_USER=lordxzi
      - FREEDNS_PASSWORD=/var/run/secrets/freedns

secrets:
  freedns:
    external: true
