apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  {{- include "powerpi.labels" . }}
spec:
  selector:
    matchLabels:
    {{- include "powerpi.selector" . | indent 4 }}
  template:
    metadata:
    {{- include "powerpi.labels" . | indent 4 }}
    spec:
      containers:
      - name: nginx
        image: twilkin/powerpi-nginx:{{ .Chart.AppVersion }}
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 25Mi
          limits:
            cpu: 1
            memory: 100Mi
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
