// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'darkbackground': string;
  'darkchartline': string;
  'darkfilterbackground': string;
  'darkfiltertext': string;
  'darkhighlight': string;
  'darkmenu': string;
  'darktext': string;
  'lightbackground': string;
  'lightchartline': string;
  'lightfilterbackground': string;
  'lightfiltertext': string;
  'lighthighlight': string;
  'lightmenu': string;
  'lighttext': string;
}
export const cssExports: CssExports;
export default cssExports;
