{{- $data := dict
    "Name" "api-policy"
    "Label" .Chart.Name
    "Mosquitto" true
    "Database" true
    "IngressController" 3000
    "External" true
}}
{{- include "powerpi.network-policy" (merge (dict "Params" $data) .) -}}
