{{- $data := dict
  "Secret" (list
    (dict
      "Name" "ihd-secret"
      "Env" (list
        (dict
          "Name" "IHD_SECRET_FILE"
          "SubPath" "ihd"
        )
      )
    )
  )
}}
{{- include "powerpi.deployment" (merge (dict "Params" $data) . )}}
