apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifx-controller
  {{- include "powerpi.labels" $ }}
spec:
  selector:
    matchLabels:
      {{- include "powerpi.selector" $ | indent 4 }}
  template:
    metadata:
      {{- include "powerpi.labels" $ | indent 4 }}
    spec:
      containers:
      - name: lifx-controller
        image: twilkin/powerpi-lifx-controller:{{ .Chart.AppVersion }}
        env:
        {{- include "powerpi.config.env.controller" . | indent 6 }}
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 100Mi
        volumeMounts:
        {{- include "powerpi.config.volumeMounts" . | indent 6 }}
      volumes:
      {{- include "powerpi.config.volumes" . | indent 4 }}
