apiVersion: apps/v1
kind: Deployment
metadata:
  name: energenie-controller
spec:
  template:
    spec:
      nodeSelector:
        powerpi-energenie: "true"
      containers:
      - name: energenie-controller
        image: twilkin/powerpi-energenie-controller
        env:
        - name: DEVICE_FATAL
          value: "true"
        - name: ENERGENIE_DEVICE
          valueFrom:
            configMapKeyRef:
              name: settings
              key: ENERGENIE_DEVICE
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
            smarter-devices/gpiomem: 1
          limits:
            cpu: 1
            memory: 100Mi
            smarter-devices/gpiomem: 1
