apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml

commonLabels:
  app.kubernetes.io/name: energenie-controller
  app.kubernetes.io/version: 0.1.11
  app.kubernetes.io/component: controller

images:
- name: twilkin/powerpi-energenie-controller
  newTag: 0.1.11
