{{- $data := dict
  "Kind" "DaemonSet"
  "Name" "node-controller"
  "Image" (.Values.Image | default "twilkin/powerpi-node-controller")
  "NodeSelector" (list
    (dict
      "Name" "powerpi-pijuice"
      "Value" "false"
    )
    (dict
      "Name" "powerpi-pwm"
      "Value" "false"
    )
  )
}}
{{- include "powerpi.controller" (merge (dict "Params" $data) . )}}

{{- if eq .Values.global.pijuice true }}
{{- $pijuice := (merge (dict
  "Name" "node-controller-pijuice"
  "NodeSelector" (list
    (dict
      "Name" "powerpi-pijuice"
      "Value" "true"
    )
    (dict
      "Name" "powerpi-pwm"
      "Value" "false"
    )
  )
  "Env" (list
    (dict
      "Name" "DEVICE_FATAL"
      "Value" (true | quote)
    )
  )
  "Resources" (list
    (dict
      "Name" "smarter-devices/i2c-1"
      "Value" 1
    )
  )
) $data)
}}
---
{{- include "powerpi.controller" (merge (dict "Params" $pijuice) . )}}
{{- end }}

{{- if eq .Values.global.pwm true }}
{{- $pwm := (merge (dict
  "Name" "node-controller-pwm"
  "NodeSelector" (list
    (dict
      "Name" "powerpi-pijuice"
      "Value" "false"
    )
    (dict
      "Name" "powerpi-pwm"
      "Value" "true"
    )
  )
  "Env" (list
    (dict
      "Name" "DEVICE_FATAL"
      "Value" (true | quote)
    )
  )
  "Resources" (list
    (dict
      "Name" "smarter-devices/gpiomem"
      "Value" 1
    )
  )
) $data)
}}
---
{{- include "powerpi.controller" (merge (dict "Params" $pwm) . )}}
{{- end }}

{{- if and (eq .Values.global.pijuice true) (eq .Values.global.pwm true) }}
{{- $both := (merge (dict
  "Name" "node-controller-pijuice-pwm"
  "NodeSelector" (list
    (dict
      "Name" "powerpi-pijuice"
      "Value" "true"
    )
    (dict
      "Name" "powerpi-pwm"
      "Value" "true"
    )
  )
  "Env" (list
    (dict
      "Name" "DEVICE_FATAL"
      "Value" (true | quote)
    )
  )
  "Resources" (list
    (dict
      "Name" "smarter-devices/gpiomem"
      "Value" 1
    )
    (dict
      "Name" "smarter-devices/i2c-1"
      "Value" 1
    )
  )
) $data)
}}
---
{{- include "powerpi.controller" (merge (dict "Params" $both) . )}}
{{- end }}
