// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'close': string;
  'content': string;
  'dialog': string;
  'header': string;
}
export const cssExports: CssExports;
export default cssExports;
