apiVersion: apps/v1
kind: Deployment
metadata:
  name: freedns
spec:
  template:
    spec:
      containers:
      - name: freedns
        image: twilkin/powerpi-freedns
        env:
        - name: FREEDNS_USER
          valueFrom:
            secretKeyRef:
              name: freedns-secret
              key: username
        - name: FREEDNS_PASSWORD
          value: /var/run/secrets/powerpi_freedns/password
        resources:
          requests:
            cpu: 50m
            memory: 350Mi
          limits:
            cpu: 1
            memory: 500Mi
        volumeMounts:
        - name: freedns-secret
          mountPath: /var/run/secrets/powerpi_freedns
          readOnly: true
      volumes:
      - name: freedns-secret
        secret:
          secretName: freedns-secret
