// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'battery': string;
  'icon': string;
  'sensors': string;
  'state': string;
  'time': string;
  'title': string;
  'tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
