// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charging': string;
  'empty': string;
  'full': string;
  'half': string;
  'icon': string;
  'low': string;
  'outdated': string;
  'quarter': string;
  'three-quarter': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
