{{- $data := dict
  "Schedule" (.Values.schedule | default "*/5 * * * *")
  "Command" (list "yarn")
  "Args" (list 
    "workspace"
    "@powerpi/freedns"
    "start:prd"
  )
  "Secret" (list
    (dict
      "Name" "freedns-secret"
      "Env" (list
        (dict
          "Name" "FREEDNS_USER"
          "Key" "username"
        )
        (dict
          "Name" "FREEDNS_PASSWORD"
          "SubPath" "password"
        )
      )
    )
  )
-}}
{{- include "powerpi.cron-job" (merge (dict "Params" $data) . ) -}}
