{{- $data := dict
  "Secret" (list
    (dict
      "Name" "freedns-secret"
      "SubPath" "password"
      "Env" (list
        (dict
          "Name" "FREEDNS_USER"
          "Key" "username"
        )
        (dict
          "Name" "FREEDNS_PASSWORD"
        )
      )
    )
  )
}}
{{- include "powerpi.deployment" (merge (dict "Params" $data) . )}}
