apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-fantastic
spec:
  template:
    spec:
      containers:
      - name: light-fantastic
        image: twilkin/powerpi-light-fantastic
        resources:
          requests:
            cpu: 50m
            memory: 400Mi
          limits:
            cpu: 1
            memory: 600Mi
