version: "3.3"

services:
  mosquitto:
    image: arm32v6/eclipse-mosquitto:1.6.12
    ports:
      - "1883:1883"
    deploy:
      replicas: 1
    volumes:
      - /var/lib/docker-volumes/mosquitto/data:/mosquitto/data
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf
  
  deep-thought:
    build: ../deep-thought
    image: ${REGISTRY}/powerpi/deep-thought:0.3.0
    deploy:
      replicas: 1
    depends_on:
      - mosquitto
    environment:
      - MQTT_ADDRESS=mqtt://mosquitto:1883
      - TOPIC_BASE=powerpi
      - DEVICES_FILE=/devices.json
    configs:
      - source: devices_config
        target: /devices.json
  
  power-starter:
    build: ../power-starter
    image: ${REGISTRY}/powerpi/power-starter:0.5.4
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.energenie == true
    depends_on:
      - mosquitto
    environment:
      - DEVICE_FATAL=true
      - MQTT_ADDRESS=mqtt://mosquitto:1883
      - TOPIC_BASE=powerpi
      - POLL_FREQUENCY=120
      - DEVICES_FILE=/devices.json
      - EVENTS_FILE=/events.json
    volumes:
      - type: bind
        source: /dev/gpiomem
        target: /dev/gpiomem
    configs:
      - source: devices_config
        target: /devices.json
      - source: events_config
        target: /events.json
  
  light-fantastic:
    build: ../light-fantastic
    image: ${REGISTRY}/powerpi/light-fantastic:0.1.5
    deploy:
      replicas: 1
    environment:
      - DEVICES_FILE=/devices.json
      - SCHEDULES_FILE=/schedules.json
    configs:
      - source: devices_config
        target: /devices.json
      - source: schedules_config
        target: /schedules.json
  
  freedns:
    build: ../freedns
    image: ${REGISTRY}/powerpi/freedns:0.0.5
    deploy:
      replicas: 1
    secrets:
      - freedns
    environment:
      - FREEDNS_USER=${FREEDNS_USER}
      - FREEDNS_PASSWORD=/var/run/secrets/freedns
  
  nginx:
    build: ../nginx
    image: ${REGISTRY}/powerpi/nginx:0.0.3
    ports:
      - "3001:80"
      - "3000:443"
    deploy:
      replicas: 1
    depends_on:
      - deep-thought
    secrets:
      - powerpi_users
    volumes:
      - /var/lib/docker-volumes/certbot/conf:/etc/letsencrypt
      - /var/lib/docker-volumes/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    build: ../certbot
    image: ${REGISTRY}/powerpi/certbot:0.0.2
    deploy:
      replicas: 1
    depends_on:
      - nginx
    environment:
      - EXTERNAL_HOST_NAME=${EXTERNAL_HOST_NAME}
      - EMAIL=${EMAIL}
    volumes:
      - /var/lib/docker-volumes/certbot/conf:/etc/letsencrypt
      - /var/lib/docker-volumes/certbot/www:/var/www/html

secrets:
  freedns:
    external: true
  powerpi_users:
    external: true

configs:
  mosquitto_config:
    file: ./config/mosquitto.conf
  devices_config:
    file: ./config/devices.json
  events_config:
    file: ./config/events.json
  schedules_config:
    file: ./config/schedules.json
