version: "3.7"

services:
  mosquitto:
    image: arm32v6/eclipse-mosquitto:1.6.7
    ports:
      - "1883:1883"
    deploy:
      replicas: 1
  
  mqtt-rest:
    image: 127.0.0.1:5000/powerpi/mqtt-rest:0.1.0
    deploy:
      replicas: 1
    depends_on:
      - mosquitto
    environment:
      - MQTT_ADDRESS=mqtt://mosquitto:1883
      - TOPIC_BASE=powerpi
  
  power-starter:
    image: 127.0.0.1:5000/powerpi/power-starter:0.5.1
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.energenie == true
    depends_on:
      - mosquitto
    environment:
      - MQTT_ADDRESS=mqtt://mosquitto:1883
      - TOPIC_BASE=powerpi
      - DEVICES_FILE=/devices
      - EVENTS_FILE=/events
    volumes:
      - type: bind
        source: /dev/gpiomem
        target: /dev/gpiomem
    configs:
      - devices
      - events
  
  light-fantastic:
    image: 127.0.0.1:5000/powerpi/light-fantastic:0.1.3
    deploy:
      replicas: 1
    environment:
      - DEVICES_FILE=/devices
      - SCHEDULES_FILE=/schedules
    configs:
      - devices
      - schedules
  
  freedns:
    image: 127.0.0.1:5000/powerpi/freedns:0.0.4
    deploy:
      replicas: 1
    secrets:
      - freedns
    environment:
      - FREEDNS_USER=${FREEDNS_USER}
      - FREEDNS_PASSWORD=/var/run/secrets/freedns
  
  nginx:
    image: 127.0.0.1:5000/powerpi/nginx:0.0.2
    ports:
      - "80:80"
      - "3000:443"
    deploy:
      replicas: 1
    depends_on:
      - mqtt-rest
    secrets:
      - powerpi_users
    volumes:
      - /var/lib/docker-volumes/certbot/conf:/etc/letsencrypt
      - /var/lib/docker-volumes/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: 127.0.0.1:5000/powerpi/certbot:0.0.2
    deploy:
      replicas: 1
    depends_on:
      - nginx
    environment:
      - EXTERNAL_HOST_NAME=${EXTERNAL_HOST_NAME}
      - EMAIL=${EMAIL}
    volumes:
      - /var/lib/docker-volumes/certbot/conf:/etc/letsencrypt
      - /var/lib/docker-volumes/certbot/www:/var/www/html

secrets:
  freedns:
    external: true
  powerpi_users:
    external: true

configs:
  devices:
    file: ./config/devices.json
  events:
    file: ./config/events.json
  schedules:
    file: ./config/schedules.json
