apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
  type: NodePort
  ports:
  - name: nginx
    protocol: TCP
    port: 3000
    targetPort: https
