user api
topic read powerpi/config/#
topic read powerpi/device/#
topic read powerpi/event/#
topic readwrite powerpi/device/+/change

user config
topic readwrite powerpi/config/#

user controller
topic readwrite powerpi/device/#
topic readwrite powerpi/event/#
topic read powerpi/geofence/#

user network_controller
topic readwrite powerpi/device/#
topic readwrite powerpi/event/#
topic readwrite powerpi/presence/#
topic read powerpi/geofence/#

user virtual_controller
topic readwrite powerpi/device/#
topic readwrite powerpi/event/#
topic read powerpi/presence/#
topic readwrite powerpi/geofence/#

user device
topic read powerpi/device/+/change
topic readwrite powerpi/device/+/status
topic readwrite powerpi/device/+/capability

user event
topic read powerpi/device/#
topic read powerpi/event/#
topic readwrite powerpi/device/+/change
topic readwrite powerpi/device/+/scene
topic read powerpi/presence/#
topic read powerpi/geofence/#

user persistence
topic read powerpi/config/#
topic read powerpi/device/#
topic read powerpi/event/#

user scheduler
topic read powerpi/device/#
topic read powerpi/event/#
topic readwrite powerpi/device/+/change
topic read powerpi/presence/#
topic read powerpi/geofence/#

user sensor
topic read powerpi/config/#
topic readwrite powerpi/event/#
