from .snapcast_client_listener import SnapcastClientListener
from .snapcast_group_listener import SnapcastGroupListener
from .snapcast_server_listener import SnapcastServerListener

SnapcastListener = SnapcastClientListener | SnapcastGroupListener | SnapcastServerListener
