{{- if or (eq .Values.global.energenie true) (eq .Values.global.zigbee true) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: smarter-device-manager-config
  {{- include "powerpi.labels.no-version" . }}
data:
  device-config.yaml: |-
{{ .Files.Get "device-config.yaml" | indent 4 }}
{{- end }}
