{{- define "powerpi.config-map" }}
{{- $name := printf "config-%s" (.Params.File | base | trimSuffix ".json") }}
{{- $existing := lookup "v1" "ConfigMap" .Release.Namespace $name }}

{{- $checksumAnnotation := printf "checksum/%s" $name }}
{{- $checksum := dig "metadata" "annotations" $checksumAnnotation "" $existing }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  {{- include "powerpi.labels.no-version" . }}
{{- if and .Values.global.config $checksum }}
  annotations:
    {{ $checksumAnnotation }}: {{ $checksum }}
{{- end }}
data:
{{- if and .Values.global.config $existing }}
{{ $existing.data | toYaml | indent 4 }}
{{- else }}
  {{ base .Params.File }}: |
{{ .Params.Content | toString | indent 4 }}
{{- end }}
{{- end }}

{{- $exclude := list }}
{{- if not .Values.global.event }}{{- $exclude = append $exclude "events" }}{{- end }}
{{- if not .Values.global.scheduler }}{{- $exclude = append $exclude "schedules" }}{{- end }}

{{- range $path, $content := .Files.Glob "config/*.json" }}
{{- $name := $path | base | trimSuffix ".json" }}
{{- if not (has $name $exclude) }}
---
{{- include "powerpi.config-map" (merge (dict "Params" (dict "File" $path "Content" $content)) $) }}
{{- end }}
{{- end }}
