{{- define "powerpi.config-map" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ .Params.File | base | trimSuffix ".json" }}
  {{- include "powerpi.labels.no-version" . }}
{{- if eq .Values.global.config true }}
  annotations:
    helm.sh/resource-policy: keep
{{- end }}
data:
  {{ base .Params.File }}: |
{{ .Params.Content | toString | indent 4 }}
{{- end }}

{{- $exclude := list }}
{{- if not .Values.global.event }}{{- $exclude = append $exclude "events" }}{{- end }}
{{- if not .Values.global.scheduler }}{{- $exclude = append $exclude "schedules" }}{{- end }}

{{- range $path, $content := .Files.Glob "config/*.json" }}
{{- $name := $path | base | trimSuffix ".json" }}
{{- if not (has $name $exclude) }}
---
{{- include "powerpi.config-map" (merge (dict "Params" (dict "File" $path "Content" $content)) $) }}
{{- end }}
{{- end }}
