{{- if eq .Values.global.useSSL true }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  {{- include "powerpi.labels" $ }}
spec:
  acme:
    {{- if eq .Values.global.env "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.global.certificateEmail }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: public
{{- end }}
