# By default deny all traffic
{{- if .Values.global.useNetworkPolicies -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  {{- include "powerpi.labels" . }}
spec:
  podSelector: {}

  policyTypes:
  - Ingress
  - Egress
---
{{- end }}
# Allow the controllers to access the message queue
{{- $data := dict
    "Name" "controller-policy"
    "Component" "controller"
    "Mosquitto" true
}}
{{ include "powerpi.network-policy" (merge (dict "Params" $data) .) }}
