# By default deny all traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  {{- include "powerpi.labels" . }}
spec:
  podSelector: {}

  policyTypes:
  - Ingress
  - Egress
---
# Allow the controllers to access the message queue
{{- 
    $messageQueue := list
      (dict
        "Component" "message-queue"
        "Port" 1883
      )
-}}

{{- $data := dict
    "Name" "controller-mosquitto"
    "Component" "controller"
    "Egress" $messageQueue
}}
{{ include "powerpi.network-policy" (merge (dict "Params" $data) .) }}
