{{- $data := dict
  "Ports" (list (dict
    "Name" "http"
    "Port" 3000
  ))
  "UseConfig" true
  "UseDevicesFile" true
  "MqttSecret" "mosquitto-voice-secret"
  "Probe" (dict
    "Http" "/health"
    "ReadinessInitialDelay" 10
    "LivenessInitialDelay" 20
  )
-}}
{{- include "powerpi.deployment" (merge (dict "Params" $data) . ) -}}
