{{- $data := dict
  "Ports" (list (dict
    "Name" "http"
    "Port" 3000
  ))
  "UseConfig" true
  "UseDevicesFile" true
  "MqttSecret" "mosquitto-voice-secret"
-}}
{{- include "powerpi.deployment" (merge (dict "Params" $data) . ) -}}
