{{- $data := dict
    "Name" "voice-assistant-policy"
    "Label" .Chart.Name
    "External" true
    "IngressController" true
}}
{{- include "powerpi.network-policy" (merge (dict "Params" $data) .) -}}
