{{- $data := dict
    "Name" "snapcast-controller-policy"
    "Label" .Chart.Name
    "Local" (dict 
        "Direction" "egress"
        "Cidr" .Values.localCIDR
        "Port" 1705
    )
}}
{{- include "powerpi.network-policy" (merge (dict "Params" $data) .) -}}
