// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'loading': string;
  'off': string;
  'on': string;
  'slide': string;
  'slider': string;
  'slider-bar': string;
  'spin': string;
  'unknown': string;
}
export const cssExports: CssExports;
export default cssExports;
