// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'darkBackground': string;
  'darkChart': string;
  'darkChartLine': string;
  'darkFilterBackground': string;
  'darkFilterText': string;
  'darkHighlight': string;
  'darkMenu': string;
  'darkMenuBorder': string;
  'darkText': string;
  'lightBackground': string;
  'lightChart': string;
  'lightChartLine': string;
  'lightFilterBackground': string;
  'lightFilterText': string;
  'lightHighlight': string;
  'lightMenu': string;
  'lightMenuBorder': string;
  'lightText': string;
}
export const cssExports: CssExports;
export default cssExports;
