// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clickable': string;
  'dialog': string;
  'gear': string;
}
export const cssExports: CssExports;
export default cssExports;
