# the component label for the main chart
component: powerpi

global:
  # the environment to deploy for "production" or "dev"
  env: production

  # whether to use SSL for the UI, API and voice integration
  useSSL: false

  # whether PowerPi is deployed in a kubernetes cluster (i.e. has more than 1 node)
  useCluster: false

  # whether to allow access to the message queue from outside of kubernetes (to support external sensors publishing events or computer devices using the shutdown service)
  useSensors: false

  # whether to enable network policies to restrict traffic between services, only disable when diagnosing issues
  useNetworkPolicies: true

  # whether to include the config-server service to get configuration from GitHub
  config: false

  # whether to include the persistence service to store messages in a database
  persistence: false

  # whether to include the event service to perform actions in reaction to events
  event: false

  # whether to include the scheduler service to update devices on a schedule
  scheduler: false

  # whether to include the voice assistant service for Alexa integration
  voiceAssistant: false

  # whether to include Energenie support
  energenie: false

  # whether to include Logitech Harmony support
  harmony: false

  # whether to include LIFX support
  lifx: false

  # whether to include ZigBee support
  zigbee: false

  # whether to include control of networked devices (i.e. computers)
  network: false

  # whether to include control on Snapcast clients
  snapcast: false

  # whether to include N3rgy energy monitoring support
  energyMonitor: false

config-server:
  # the path to the config files in the GitHub repo
  path: "kubernetes/config"

energenie-controller:
  # the Energenie device type to use, either ENER314-RT or ENER314
  type: "ENER314-RT"

mosquitto:
  # the IP address range of internal networks, used to restrict access from outside to mosquitto
  localCIDR:
    - 10.0.0.0/8
    - 172.16.0.0/20
    - 192.168.0.0/16

harmony-controller:
  # the IP address range of internal networks, used to restrict access only to the Harmony Hub(s)
  localCIDR:
    - 10.0.0.0/8
    - 172.16.0.0/20
    - 192.168.0.0/16

lifx-controller:
  # the IP address range of internal networks, used to restrict access only to the LIFX device(s)
  localCIDR:
    - 10.0.0.0/8
    - 172.16.0.0/20
    - 192.168.0.0/16

network-controller:
  # the IP of internal networks, used to restrict access only to the internal broadcast address
  localCIDR:
    - 10.0.0.0/8
    - 172.16.0.0/20
    - 192.168.0.0/16

snapcast-controller:
  # the IP address range of internal networks, used to restrict access only to the Snapcast server(s)
  localCIDR:
    - 10.0.0.0/8
    - 172.16.0.0/20
    - 192.168.0.0/16

zigbee-controller:
  # Device configuration for ZigBee controller
  # Use "socket://<host>:<port>" for network devices or "/dev/ttyACM0" for USB devices
  device: "/dev/ttyACM0"
