# the component label for the main chart
component: powerpi

global:
  # the environment to deploy for "production" or "dev"
  env: production

  # whether to use SSL for the UI, API and voice integration
  useSSL: false

  # whether PowerPi is deployed in a kubernetes cluster (i.e. has more than 1 node)
  useCluster: false

  # whether to allow access to the message queue from outside of kubernetes (to support external sensors publishing events or computer devices using the shutdown service)
  useSensors: false

  # the name of a ClusterIssuer to use to request certificates
  clusterIssuer: null

  # whether to use FreeDNS or not
  freeDNS: false

  # whether to include the config-server service to get configuration from GitHub
  config: false

  # whether to include the persistence service to store messages in a database
  persistence: false

  # whether to include the scheduler service to update devices on a schedule
  scheduler: false

  # whether to include the voice assistant service for Alexa integration
  voiceAssistant: false

  # whether to include Energenie support
  energenie: false

  # whether to include Logitech Harmony support
  harmony: false

  # whether to include LIFX support
  lifx: false

  # whether to include ZigBee support
  zigbee: false

  # whether to include control of networked devices (i.e. computers)
  network: false

  # whether to include control on Snapcast clients
  snapcast: false

  # whether to include N3rgy energy monitoring support
  energyMonitor: false

config-server:
  # the path to the config files in the GitHub repo
  path: "kubernetes/config"

energenie-controller:
  # the Energenie device type to use, either ENER314-RT or ENER314
  type: "ENER314-RT"
