{{/* Required: Wake-on-LAN needs to send UDP broadcast packets on the local network,
     which requires hostNetwork. */}}
{{-
    $data := dict
    "HostNetwork" (true | quote)
    "Env" (list
        (dict
            "Name" "MQTT_ADDRESS"
            "Value" (print "mqtts://" .Values.global.mosquittoHostName ":8883")
        )
    )
-}}

{{- include "powerpi.controller" (merge (dict "Params" $data) . ) -}}
