// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'device': string;
  'device-filters': string;
  'device-list': string;
  'device-state': string;
}
export const cssExports: CssExports;
export default cssExports;
