// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'history-filters': string;
  'history-list': string;
  'loading': string;
}
export const cssExports: CssExports;
export default cssExports;
