apiVersion: apps/v1
kind: Deployment
metadata:
  name: babel-fish
  {{- include "powerpi.labels" $ }}
spec:
  selector:
    matchLabels:
      {{- include "powerpi.selector" $ | indent 4 }}
  template:
    metadata:
      {{- include "powerpi.labels" $ | indent 4 }}
    spec:
      containers:
      - name: babel-fish
        image: twilkin/powerpi-babel-fish:{{ .Chart.AppVersion }}
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 200Mi
