apiVersion: v1
kind: Service
metadata:
  name: babel-fish
  {{- include "powerpi.labels" $ }}
spec:
  type: ClusterIP
  selector:
    {{- include "powerpi.selector" $ | indent 2 }}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
