apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: powerpi-storage
