apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: mqtt
