apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
spec:
  template:
    spec:
      nodeSelector:
        powerpi-storage: "true"
      priorityClassName: powerpi-critical
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 100Mi
        volumeMounts:
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-volume-claim
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
