apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-fantastic
  {{- include "powerpi.labels" . }}
spec:
  selector:
    matchLabels:
    {{- include "powerpi.selector" . | indent 4 }}
  template:
    metadata:
    {{- include "powerpi.labels" . | indent 4 }}
    spec:
      containers:
      - name: light-fantastic
        image: twilkin/powerpi-light-fantastic:{{ .Chart.AppVersion }}
        env:
        {{- include "powerpi.config.env" . | indent 6 }}
        {{- include "powerpi.config.env.devices" . | indent 6 }}
        {{- include "powerpi.config.env.schedules" . | indent 6 }}
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 200Mi
        volumeMounts:
        {{- include "powerpi.config.volumeMounts" . | indent 6 }}
      volumes:
      {{- include "powerpi.config.volumes" . | indent 4 }}
