{{- $needsNodeSelector := include "powerpi.persistent-volume-node-selector" . -}}
{{- $nodeSelector := ternary (list
  (dict
    "Name" $needsNodeSelector
    "Value" "true"
  )
) (list) (not (empty $needsNodeSelector))
-}}

{{- $data := dict
  "Name" "database-backup"
  "Image" "postgres"
  "RunAsUser" 70
  "FsGroup" 70
  "RequestMemory" "50Mi"
  "NodeSelector" $nodeSelector
  "Schedule" (.Values.backupSchedule | default "5 23 * * *")
  "ActiveDeadlineSeconds" (.Values.backupTimeout | default 300)
  "ConcurrencyPolicy" "Forbid"
  "Command" (list "/bin/sh")
  "Args" (list 
    "-c"
    "{ printf 'database:5432:*:*:'; cat $PGPASSWORD_FILE; } > /tmp/.pgpass && chmod 600 /tmp/.pgpass && PGPASSFILE=/tmp/.pgpass pg_dump --host=database --data-only --compress=9 --file=/srv/backup/$(date +%Y-%m-%d-%H-%M)-powerpi.sql.gz"
  )
  "PersistentVolumeClaim" (dict
    "Name" "database-backup-data"
    "Claim" "database-backup-volume-claim"
    "Path" "/srv/backup"
  )
  "Secret" (list
    (dict
      "Name" "database-secret"
      "Env" (list
        (dict
          "Name" "PGDATABASE"
          "Key" "schema"
        )
        (dict
          "Name" "PGUSER"
          "Key" "username"
        )
        (dict
          "Name" "PGPASSWORD_FILE"
          "SubPath" "password"
        )
      )
    )
  )
}}

{{- include "powerpi.job" (merge (dict "Params" $data) . ) }}
