{{- $services := list
  (dict
    "Label" "api"
    "Port" 5432
  )
  (dict
    "Label" "persistence"
    "Port" 5432
  )
}}

{{- $data := dict
    "Name" "database-ingress"
    "Label" "database"
    "Ingress" $services
}}
{{ include "powerpi.network-policy" (merge (dict "Params" $data) .) }}
