{{- $components := list
  (dict
    "Component" "api"
    "Port" 5432
  )
  (dict
    "Component" "persistence"
    "Port" 5432
  )
}}

{{- $data := dict
    "Name" "database-ingress"
    "Component" "database"
    "Ingress" $components
}}
{{ include "powerpi.network-policy" (merge (dict "Params" $data) .) }}
