apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
  {{- include "powerpi.labels" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: powerpi-storage
