apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  schema: {{ "powerpi" | b64enc | quote }}
  username: {{ "powerpi" | b64enc | quote }}
  {{- include "powerpi.generate-secret" (merge (dict "Params" (dict
    "Name" "database-secret"
    "Key" "password"
  )) . )}}
