apiVersion: apps/v1
kind: Deployment
metadata:
  name: babel-fish
spec:
  template:
    spec:
      containers:
      - name: babel-fish
        image: twilkin/powerpi-babel-fish
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 450Mi
          limits:
            cpu: 1
            memory: 600Mi
