apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmony-controller
spec:
  template:
    spec:
      containers:
      - name: harmony-controller
        image: twilkin/powerpi-harmony-controller
        resources:
          requests:
            cpu: 50m
            memory: 75Mi
          limits:
            cpu: 1
            memory: 200Mi
