[tool.poetry]
name = "powerpi-common-test"
version = "0.2.1"
description = "PowerPi Common Python Test Library"
license = "GPL-3.0-only"
authors = ["TWilkin <4322355+TWilkin@users.noreply.github.com>"]
repository = "https://github.com/TWilkin/powerpi.git"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "~=6.2.2"
pytest-asyncio = "~=0.16.0"
pytest-cov = "~=3.0.0"
pytest-mock = "~=3.5.1"

[tool.poetry.dev-dependencies]
autopep8 = "~=1.6.0"
pylint = "~=2.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
