[tool.poetry]
name = "powerpi-common-test"
version = "0.6.0"
description = "PowerPi Common Python Test Library"
license = "GPL-3.0-only"
authors = ["TWilkin <4322355+TWilkin@users.noreply.github.com>"]
repository = "https://github.com/TWilkin/powerpi.git"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "~=7.4.2"
pytest-asyncio = "~=0.21.1"
pytest-cov = "~=4.1.0"
pytest-mock = "~=3.11.1"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
