[tool.poetry]
name = "powerpi-common-test"
version = "0.2.3"
description = "PowerPi Common Python Test Library"
license = "GPL-3.0-only"
authors = ["TWilkin <4322355+TWilkin@users.noreply.github.com>"]
repository = "https://github.com/TWilkin/powerpi.git"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "~=7.1.3"
pytest-asyncio = "~=0.19.0"
pytest-cov = "~=3.0.0"
pytest-mock = "~=3.8.2"

[tool.poetry.dev-dependencies]
autopep8 = "~=1.7.0"
pylint = "~=2.15.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
