apiVersion: apps/v1
kind: Deployment
metadata:
  name: macro-controller
spec:
  template:
    spec:
      containers:
      - name: macro-controller
        image: twilkin/powerpi-macro-controller
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 1
            memory: 100Mi
