apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml

commonLabels:
  app.kubernetes.io/name: macro-controller
  app.kubernetes.io/version: 1.1.13
  app.kubernetes.io/component: controller

images:
- name: twilkin/powerpi-macro-controller
  newTag: 1.1.13
