apiVersion: v1
kind: Service
metadata:
  name: database
  {{- include "powerpi.labels" $ }}
spec:
  selector:
    {{- include "powerpi.selector" $ | indent 2 }}
  type: ClusterIP
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: postgres
