// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'custom': string;
  'disabled': string;
}
export const cssExports: CssExports;
export default cssExports;
