apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
spec:
  template:
    spec:
      containers:
      - name: persistence
        image: twilkin/powerpi-persistence
        env:
        - name: DB_HOST
          value: database
        - name: DB_SCHEMA
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: schema
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: DB_SECRET_FILE
          value: /var/run/secrets/powerpi_database/password
        volumeMounts:
        - name: database-secret
          mountPath: /var/run/secrets/powerpi_database
          readOnly: true
      volumes:
      - name: database-secret
        secret:
          secretName: database-secret
