[tool.poetry]
name = "harmony_controller"
version = "0.1.2"
description = "PowerPi Logitech Harmony Controller"
license = "GPL-3.0-only"
authors = ["TWilkin <4322355+TWilkin@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
async-cache = "~=1.1.1"
lazy = "~=1.4"
powerpi-common = {path = "../../common/python", develop = true}
pyharmony = "~=1.0.21"

[tool.poetry.dev-dependencies]
autopep8 = "~=1.6.0"
powerpi-common-test = {path = "../../common/pytest", develop = true}
pylint = "~=2.12.2"
pytest-ordering = "~=0.6"

[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple/"

[tool.pytest.ini_options]
addopts = "-v --cov=harmony_controller"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
