// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'floor': string;
  'layout': string;
  'rotate': string;
  'visible': string;
  'wide': string;
}
export const cssExports: CssExports;
export default cssExports;
