{{- $ssl := eq (include "powerpi.mosquitto-ssl" .) "true" -}}
{{- if $ssl -}}

{{- $data := dict
  "Name" "mosquitto-cert"
  "HostName" .Values.global.mosquittoHostName
-}}

{{- include "powerpi.certificate" (merge (dict "Params" $data) . ) -}}

{{- end -}}
