apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  {{- include "powerpi.labels.no-version" . }}
data:
  mosquitto.conf: |- 
{{ .Files.Get "mosquitto.conf" | indent 4 }}
  acl.conf: |- 
{{ .Files.Get "acl.conf" | indent 4 }}
  entry-point.sh: |-
{{ .Files.Get "entry-point.sh" | indent 4 }}
