apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  {{- include "powerpi.labels.no-version" . }}
data:
  mosquitto.conf: |- 
{{ .Files.Get "mosquitto.conf" | indent 4 }}
{{- if and 
    (eq .Values.global.useSSL true) 
    (eq .Values.global.useSensors true) 
    (not (eq .Values.global.clusterIssuer nil)) 
    (not (eq .Values.hostName nil)) 
}}
{{ .Files.Get "mosquitto-ssl.conf" | indent 4 }}
{{- end }}
  acl.conf: |- 
{{ .Files.Get "acl.conf" | indent 4 }}
