apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  {{- include "powerpi.labels.no-version" . }}
data:
  mosquitto.conf: |- 
{{ .Files.Get "mosquitto.conf" | indent 4 }}
{{- $ssl := eq (include "powerpi.mosquitto-ssl" .) "true" -}}
{{- if $ssl }}
{{ .Files.Get "mosquitto-ssl.conf" | indent 4 }}
{{- end }}
  acl.conf: |- 
{{ .Files.Get "acl.conf" | indent 4 }}
