{{- $services := list
  (dict
    "Label" "api"
    "Port" 1883
  )
  (dict
    "Component" "controller"
    "Port" 1883
  )
}}

{{- if .Values.global.config }}
{{- $services = append $services (dict
  "Label" "config"
  "Port" 1883
)}}
{{- end }}

{{- if .Values.global.energyMonitor }}
{{- $services = append $services (dict
  "Label" "energy-monitor"
  "Port" 1883
)}}
{{- end }}

{{- if .Values.global.event }}
{{- $services = append $services (dict
  "Label" "event"
  "Port" 1883
)}}
{{- end }}

{{- if .Values.global.persistence }}
{{- $services = append $services (dict
  "Label" "persistence"
  "Port" 1883
)}}
{{- end }}

{{- if .Values.global.scheduler }}
{{- $services = append $services (dict
  "Label" "scheduler"
  "Port" 1883
)}}
{{- end }}

{{- if .Values.global.voiceAssistant }}
{{- $services = append $services (dict
  "Label" "voice-assistant"
  "Port" 1883
)}}
{{- end }}

{{- $data := dict
    "Name" "mosquitto-ingress"
    "Label" "mosquitto"
    "Ingress" $services
}}
{{ include "powerpi.network-policy" (merge (dict "Params" $data) .) }}
