{{- define "powerpi.generate-mosquitto-secret" -}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Params.Name) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- (get $secretData "password") | default (randAlphaNum 32) -}}
{{- end -}}

{{- define "powerpi.mosquitto-passwords" -}}
api:{{ .Params.ApiSecret }}
config:{{ .Params.ConfigSecret }}
controller:{{ .Params.ControllerSecret }}
device:{{ .Params.DeviceSecret }}
persistence:{{ .Params.PersistenceSecret }}
scheduler:{{ .Params.SchedulerSecret }}
sensor:{{ .Params.SensorSecret }}{
voice:{{ .Params.VoiceSecret }}
{{- end -}}

{{- $apiSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
    "Name" "mosquitto-api-secret"
  )) . ) -}}

{{- $configSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-config-secret"
)) . ) -}}

{{- $controllerSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-controller-secret"
)) . ) -}}

{{- $deviceSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-device-secret"
)) . ) -}}

{{- $persistenceSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-persistence-secret"
)) . ) -}}

{{- $schedulerSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-scheduler-secret"
)) . ) -}}

{{- $sensorSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-sensor-secret"
)) . ) -}}

{{- $voiceSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-voice-secret"
)) . ) -}}

{{- $hasSensors := or (eq .Values.global.useSensors true) (eq .Values.global.energyMonitor true) -}}

{{- $mosquittoPasswords := dict
  "HasSensors" $hasSensors
  "ApiSecret" $apiSecret
  "ConfigSecret" $configSecret
  "ControllerSecret" $controllerSecret
  "DeviceSecret" $deviceSecret
  "PersistenceSecret" $persistenceSecret
  "SchedulerSecret" $schedulerSecret
  "SensorSecret" $sensorSecret
  "VoiceSecret" $voiceSecret
-}}

apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-password-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  passwords: {{ include "powerpi.mosquitto-passwords" (merge (dict "Params" $mosquittoPasswords) . ) | b64enc }}
---

apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-api-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "api" | b64enc | quote }}
  password: {{ $apiSecret | b64enc | quote }}
---

{{- if eq .Values.global.config true -}}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-config-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "config" | b64enc | quote }}
  password: {{ $configSecret | b64enc | quote }}
---
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-controller-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "controller" | b64enc | quote }}
  password: {{ $controllerSecret | b64enc | quote }}
---

apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-device-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "device" | b64enc | quote }}
  password: {{ $deviceSecret | b64enc | quote }}
---

{{- if eq .Values.global.persistence true -}}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-persistence-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "persistence" | b64enc | quote }}
  password: {{ $persistenceSecret | b64enc | quote }}
---
{{- end -}}

{{- if eq .Values.global.scheduler true -}}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-scheduler-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "scheduler" | b64enc | quote }}
  password: {{ $schedulerSecret | b64enc | quote }}
---
{{- end -}}

{{- if eq $hasSensors true -}}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-sensor-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "sensor" | b64enc | quote }}
  password: {{ $sensorSecret | b64enc | quote }}
---
{{- end -}}

{{- if eq .Values.global.voiceAssistant true -}}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-voice-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: {{ "voice" | b64enc | quote }}
  password: {{ $voiceSecret | b64enc | quote }}
{{- end -}}
