{{- define "powerpi.generate-mosquitto-secret" -}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Params.Name) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
{{- (get $secretData "password") | default (randAlphaNum 32 | b64enc) -}}
{{- end -}}

{{- $apiSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
    "Name" "mosquitto-api-secret"
  )) . ) -}}

{{- $configSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-config-secret"
)) . ) -}}

{{- $controllerSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-controller-secret"
)) . ) -}}

{{- $persistenceSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-persistence-secret"
)) . ) -}}

{{- $sensorSecret := include "powerpi.generate-mosquitto-secret" (merge (dict "Params" (dict
  "Name" "mosquitto-sensor-secret"
)) . ) -}}

apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-password-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  passwords: |-
    api:{{ $apiSecret }}
    config:{{ $configSecret }}
    controller:{{ $controllerSecret }}
    persistence:{{ $persistenceSecret }}
    sensor:{{ $sensorSecret }}
---

apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-api-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: api
  password: {{ $apiSecret | quote }}
---

{{- if eq .Values.global.config true -}}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-config-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: config
  password: {{ $configSecret | quote }}
---
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-controller-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: controller
  password: {{ $controllerSecret | quote }}
---

{{- if eq .Values.global.persistence true -}}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-persistence-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: persistence
  password: {{ $persistenceSecret | quote }}
---
{{- end -}}

{{- if eq .Values.global.useSensors true -}}
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-sensor-secret
  {{- include "powerpi.labels" . }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  username: sensor
  password: {{ $sensorSecret | quote }}
---
{{- end -}}
