{{- $ssl := and 
  (eq .Values.global.useSSL true) 
  (eq .Values.global.useSensors true) 
  (not (eq .Values.global.clusterIssuer nil)) 
  (not (eq .Values.hostName nil))
-}}

{{- $type := ternary "LoadBalancer" "NodePort" (or .Values.global.useSensors $ssl) -}}

{{- $ports := list (dict
  "Name" "mqtt"
  "Port" 1883
) -}}

{{- if $ssl -}}
{{- $ports = append $ports (dict
  "Name" "mqtts"
  "Port" 8883
) -}}
{{- end -}}

{{- $data := dict
  "Type" $type
  "Ports" $ports
-}}

{{- include "powerpi.service" (merge (dict "Params" $data) .) -}}
