{{- $type := ternary "LoadBalancer" "NodePort" .Values.global.useSensors }}

{{- $data := dict
  "Type" $type
  "PortName" "mqtt"
  "Port" 1883
}}

{{- include "powerpi.service" (merge (dict "Params" $data) . )}}
