apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  {{- include "powerpi.labels" . }}
spec:
  selector:
  {{- include "powerpi.selector" . | indent 2 }}
  type: LoadBalancer
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: mqtt
