{{- $ssl := eq (include "powerpi.mosquitto-ssl" .) "true" -}}

{{- $type := ternary "LoadBalancer" "ClusterIP" (and .Values.global.useSensors (not $ssl)) -}}

{{- $data := dict
  "Type" $type
  "PortName" "mqtt"
  "Port" 1883
-}}

{{- include "powerpi.service" (merge (dict "Params" $data) .) }}
---
{{- if $ssl -}}

{{- $data = dict
  "Name" "mosquitto-ssl"
  "Type" "LoadBalancer"
  "PortName" "mqtts"
  "Port" 8883
  "LoadBalancerIP" .Values.mosquitto.loadBalancerIP
-}}

{{- include "powerpi.service" (merge (dict "Params" $data) .) -}}

{{- end -}}
