apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-server
  {{- include "powerpi.labels" . }}
rules:
  # we need to be able to update the ConfigMaps with the config from GitHub
  - apiGroups: 
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - update
    resourceNames:
    - config-devices
  {{- if .Values.global.event }}
    - config-events
  {{- end }}
    - config-floorplan
  {{- if .Values.global.scheduler }}
    - config-schedules
  {{- end }}
    - config-users

  # we need to be able to list the Deployments/StatefulSets to see the deployed services
  - apiGroups: 
    - apps
    resources:
    - deployments
    - statefulsets
    verbs:
    - list

  # we need to be able to patch the Deployments/StatefulSets to update the ConfigMap hash annotation
  - apiGroups:
    - apps
    resources: 
    - deployments
    - statefulsets
    verbs:
    - get
    - patch
    resourceNames:
    - api
    {{- if .Values.global.energyMonitor }}
    - energy-monitor
    {{- end }}
    {{- if .Values.global.event }}
    - event
    {{- end }}
    {{- if .Values.global.scheduler }}
    - scheduler
    {{- end }}
    {{- if .Values.global.voiceAssistant }}
    - voice-assistant
    {{- end }}
    {{- if .Values.global.energenie }}
    - energenie-controller
    {{- end }}
    {{- if .Values.global.harmony }}
    - harmony-controller
    {{- end }}
    {{- if .Values.global.lifx }}
    - lifx-controller
    {{- end }}
    {{- if .Values.global.network }}
    - network-controller
    {{- end }}
    {{- if .Values.global.snapcast }}
    - snapcast-controller
    {{- end }}
    - virtual-controller
    {{- if .Values.global.zigbee }}
    - zigbee-controller
    {{- end }}
