apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
  - name: mosquitto
    protocol: TCP
    port: 1883
    targetPort: mosquitto
