// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'battery': string;
  'cell': string;
  'even': string;
  'hidden': string;
  'history': string;
  'icon': string;
  'list': string;
  'narrow': string;
  'since': string;
  'state': string;
  'table': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
