name: Release PowerPi

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Configure git
      run: |
        git config user.name PowerPi-bot
        git config user.email PowerPi-Bot@github.com
    
    - name: Add chart directory
      run: ln -s kubernetes charts

    - name: Tag services
      shell: bash
      run: "${GITHUB_WORKSPACE}/.github/scripts/tag.sh"

    - name: Package and upload helm chart
      shell: bash
      run: "${GITHUB_WORKSPACE}/.github/scripts/release.sh"
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
